[profile.default]
src = "src"
out = "out"
libs = ["lib","node_modules"]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@chimera/=lib/chimera/src/',
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@uniswapContracts/=lib/v3-core/contracts/",
    "@uniswapPeriphery/=lib/v3-periphery/contracts/"
]

auto_detect_solc = true
solc_version ="0.8.23"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
